### ISSUE TITLE
header repo

### ISSUE THREAD

**Issue by EthanArbuckle** [showgp/rust-react-static-build#2]

**Comment by showgp** [comment]
> hello!
> 
> you forked one of my repos while it was erroneously set to public ( https://github.com/showgp/iPhone15-3_17.6.1_21G101_Restore). would you be willing to make your fork private? I did not intend to make it public

Sure, the forked repo is gone now.

**Comment by EthanArbuckle** [comment]
Thank you, I appreciate it

**Comment by showgp** [comment]
> Thank you, I appreciate it

Also thank you for sharing so many useful iOS repos to help someone like me(junior iOS developer)😄
